CREATE TABLE MEDICAL_JOURNAL(JOURNAL_ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY,
								ISSN CHAR(9) NOT NULL,
								NAME VARCHAR(30) NOT NULL,
								LOGO VARCHAR(150),
								TAGS VARCHAR(150),
								LANGUAGE CHAR(5) NOT NULL);
								
CREATE TABLE PUBLICATION(PUBLICATION_ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY,
							JOURNAL_ID INTEGER FOREIGN KEY REFERENCES MEDICAL_JOURNAL(JOURNAL_ID) NOT NULL,
							NAME VARCHAR(30) NOT NULL,
							AUTHORS VARCHAR(150) NOT NULL,
							PUBLICATION_DATE DATE NOT NULL,
							TAGS VARCHAR(150),
							PAPER BLOB(10M));